# -*- coding: utf-8 -*-
"""spaceship_titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZU04pO6dJngBluYAuR397HHMPXeQVVyz
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

train_df = pd.read_csv('train.csv')
train_df

train_df_sub=train_df[['CryoSleep', 'Destination', 'Age', 'VIP', 'HomePlanet', 'Transported']]
train_df_sub

"""Data preprocessing"""

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
train_df_sub['CryoSleep']=le.fit_transform(train_df_sub['CryoSleep'])
train_df_sub['Destination']=le.fit_transform(train_df_sub['Destination'])
train_df_sub['VIP']=le.fit_transform(train_df_sub['VIP'])
train_df_sub['Transported']=le.fit_transform(train_df_sub['Transported'])
train_df_sub['HomePlanet']=le.fit_transform(train_df_sub['HomePlanet'])
train_df_sub

train_df_sub.isnull().sum()

train_df_sub.info()

train_df_sub['Age'].fillna(train_df_sub['Age'].mean(), inplace=True)

train_df_sub

train_df_sub.isnull().sum()

X_train=train_df_sub.drop('Transported', axis=1)
y_train=train_df_sub['Transported']

"""Model **Selection**"""

from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=40,
    n_jobs=-1
)
rf.fit(X_train, y_train)

y_pred = rf.predict(X_train)
y_pred

"""Evaluation"""

from sklearn.metrics import accuracy_score
accuracy_score(y_train, y_pred)

test_df = pd.read_csv('test.csv')
test_df

test_df_sub=test_df[['CryoSleep', 'Destination', 'Age', 'HomePlanet', 'VIP']]
test_df_sub

test_df_sub.info()

from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
test_df_sub['CryoSleep']=le.fit_transform(test_df_sub['CryoSleep'])
test_df_sub['Destination']=le.fit_transform(test_df_sub['Destination'])
test_df_sub['VIP']=le.fit_transform(test_df_sub['VIP'])
test_df_sub['HomePlanet']=le.fit_transform(test_df_sub['HomePlanet'])
test_df_sub

test_df_sub.info()

test_df_sub['Age'].fillna(test_df_sub['Age'].mean(), inplace=True)


test_df_sub

X_test = test_df_sub[X_train.columns]
test_df_sub['Transported']= rf.predict(X_test)

# accuracy_score(y_train, y_pred1) # This line was removed as it compared training labels with test predictions.

test_df_sub['Transported'] = test_df_sub['Transported'].astype(bool)
test_df_sub

test_df['Transported']= test_df_sub['Transported']
test_df

test_df[['PassengerId', 'Transported']].to_csv('random_forest_submission3.csv', index=False)

